import type { LotteryDef } from '../types/lottery';

export const LOTTERY_DEFS: Record<string, LotteryDef> = {
  lotto_max: {
    id: 'lotto_max',
    name: 'Lotto Max',
    country: 'CA',
    draw_frequency: 'weekly',
    main_count: 7,
    main_min: 1,
    main_max: 49,
    special_count: 1,
    special_min: 1,
    special_max: 49,
    source_url: 'https://www.olg.ca/en/lottery/play-lotto-max-encore.html',
  },
  lotto_649: {
    id: 'lotto_649',
    name: 'Lotto 6/49',
    country: 'CA',
    draw_frequency: 'weekly',
    main_count: 6,
    main_min: 1,
    main_max: 49,
    special_count: 1,
    special_min: 1,
    special_max: 49,
    source_url: 'https://www.olg.ca/en/lottery/play-lotto-649-encore.html',
  },
  powerball: {
    id: 'powerball',
    name: 'Powerball',
    country: 'US',
    draw_frequency: 'biweekly',
    main_count: 5,
    main_min: 1,
    main_max: 69,
    special_count: 1,
    special_min: 1,
    special_max: 26,
    source_url: 'https://www.powerball.com/',
  },
  mega_millions: {
    id: 'mega_millions',
    name: 'Mega Millions',
    country: 'US',
    draw_frequency: 'biweekly',
    main_count: 5,
    main_min: 1,
    main_max: 70,
    special_count: 1,
    special_min: 1,
    special_max: 25,
    source_url: 'https://www.megamillions.com/',
  },
};
