-- Loto-Québec: Extra (7 digits) for Lotto Max and Lotto 6/49
INSERT INTO add_on_catalog (game_code, jurisdiction_code, add_on_code, add_on_type, input_schema_json, rules_schema_json, official_rules_url, claim_url, is_enabled) VALUES
('lotto_max', 'CA-QC', 'EXTRA', 'INDEPENDENT_NUMBER', '{"digits":7,"userInput":true,"multipleGroups":false}', '{"matchDirection":"rightToLeft","tiers":[{"matchedDigits":7,"prize":"Jackpot"},{"matchedDigits":6,"prize":"$100"},{"matchedDigits":5,"prize":"$20"},{"matchedDigits":4,"prize":"$5"},{"matchedDigits":3,"prize":"$2"}]}', 'https://loteries.lotoquebec.com/en/lotteries/extra', 'https://loteries.lotoquebec.com/en', true),
('lotto_649', 'CA-QC', 'EXTRA', 'INDEPENDENT_NUMBER', '{"digits":7,"userInput":true,"multipleGroups":false}', '{"matchDirection":"rightToLeft","tiers":[{"matchedDigits":7,"prize":"Jackpot"},{"matchedDigits":6,"prize":"$100"},{"matchedDigits":5,"prize":"$20"},{"matchedDigits":4,"prize":"$5"},{"matchedDigits":3,"prize":"$2"}]}', 'https://loteries.lotoquebec.com/en/lotteries/extra', 'https://loteries.lotoquebec.com/en', true)
ON CONFLICT (game_code, jurisdiction_code, add_on_code) DO NOTHING;

-- Atlantic Lottery: TAG for PE and NL (already seeded for NB/NS in 004)
INSERT INTO add_on_catalog (game_code, jurisdiction_code, add_on_code, add_on_type, input_schema_json, rules_schema_json, official_rules_url, claim_url, is_enabled) VALUES
('lotto_max', 'CA-PE', 'TAG', 'INDEPENDENT_NUMBER', '{"digits":6,"userInput":true,"tagDrawDateOptional":true}', '{"matchType":"position","tiers":[{"matchedDigits":6,"prize":"Jackpot"},{"matchedDigits":5,"prize":"$1000"},{"matchedDigits":4,"prize":"$100"},{"matchedDigits":3,"prize":"$20"},{"matchedDigits":2,"prize":"$10"},{"matchedDigits":1,"prize":"$2"}]}', 'https://alc.ca/content/alc/en/our-games/lotto/tag.html', 'https://atlanticlottery.com/', true),
('lotto_max', 'CA-NL', 'TAG', 'INDEPENDENT_NUMBER', '{"digits":6,"userInput":true,"tagDrawDateOptional":true}', '{"matchType":"position","tiers":[{"matchedDigits":6,"prize":"Jackpot"},{"matchedDigits":5,"prize":"$1000"},{"matchedDigits":4,"prize":"$100"},{"matchedDigits":3,"prize":"$20"},{"matchedDigits":2,"prize":"$10"},{"matchedDigits":1,"prize":"$2"}]}', 'https://alc.ca/content/alc/en/our-games/lotto/tag.html', 'https://atlanticlottery.com/', true),
('lotto_649', 'CA-PE', 'TAG', 'INDEPENDENT_NUMBER', '{"digits":6,"userInput":true,"tagDrawDateOptional":true}', '{"matchType":"position","tiers":[{"matchedDigits":6,"prize":"Jackpot"},{"matchedDigits":5,"prize":"$1000"},{"matchedDigits":4,"prize":"$100"},{"matchedDigits":3,"prize":"$20"},{"matchedDigits":2,"prize":"$10"},{"matchedDigits":1,"prize":"$2"}]}', 'https://alc.ca/content/alc/en/our-games/lotto/tag.html', 'https://atlanticlottery.com/', true),
('lotto_649', 'CA-NL', 'TAG', 'INDEPENDENT_NUMBER', '{"digits":6,"userInput":true,"tagDrawDateOptional":true}', '{"matchType":"position","tiers":[{"matchedDigits":6,"prize":"Jackpot"},{"matchedDigits":5,"prize":"$1000"},{"matchedDigits":4,"prize":"$100"},{"matchedDigits":3,"prize":"$20"},{"matchedDigits":2,"prize":"$10"},{"matchedDigits":1,"prize":"$2"}]}', 'https://alc.ca/content/alc/en/our-games/lotto/tag.html', 'https://atlanticlottery.com/', true)
ON CONFLICT (game_code, jurisdiction_code, add_on_code) DO NOTHING;
